# permissions for end users to edit couchbaseindices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: couchbaseindex-editor-role
rules:
- apiGroups:
  - cache.forescout.com
  resources:
  - couchbaseindices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.forescout.com
  resources:
  - couchbaseindices/status
  verbs:
  - get
