
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.forescout.com
  resources:
  - couchbaseindices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.forescout.com
  resources:
  - couchbaseindices/finalizers
  verbs:
  - update
- apiGroups:
  - cache.forescout.com
  resources:
  - couchbaseindices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
