apiVersion: cache.forescout.com/v1alpha1
kind: CouchbaseIndex
metadata:
  name: sample-primary
  namespace: cb-indexcreation-operator-system
spec:
  # Add fields here
  cbClusterSecret: "cb-creds"
  indexdata:
    bucketname: "test"
    indexname: "#primary"
    isprimary: true
