apiVersion: v1
kind: Secret
metadata:
  name: cb-creds
  namespace: cb-indexcreation-operator-system
stringData:
  url: "testcluster.couchbase-operator.svc.cluster.local"
  username: "Administrator"
  password: "password"